tests: Work around undefined reference to plasmoid
In QML 6 the mock plasmoid object is no longer accessible in ReloadTimer by
implicitly being a child of the root TestCase object.